<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-21 20:44
=======
# Generated by Django 5.2 on 2025-05-21 20:19
>>>>>>> Create-Django-View-for-Add-Groups

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
