# Generated by Django 5.1.7 on 2025-03-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('FR', 'Fruits'), ('VE', 'Vegetables'), ('MT', 'Meats'), ('DA', 'Dairy'), ('HY', 'Hygiene'), ('CL', 'Cleaning'), ('FZ', 'Frozen'), ('SF', 'Sea Food'), ('PR', 'Preserves'), ('BG', 'Baked Goods')], max_length=2)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, default='food/default.jpg', upload_to='food')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroups', to='products.product')),
            ],
        ),
    ]
