# Generated by Django 5.1.7 on 2025-03-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroups', to='products.product')),
            ],
        ),
    ]
