# Generated by Django 5.1.7 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='name',
            field=models.CharField(blank='false', max_length=100),
        ),
    ]
