# Generated by Django 5.1.7 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
