# Generated by Django 5.1.7 on 2025-03-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productgroup_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
